### ISSUE TITLE
Support Multiple Meeting times for SIGs

### ISSUE THREAD

**Issue by baileytincher** [acm-uiuc/core#28]
Many SIGs/committees have multiple meeting times throughout a week. The `groups.yaml` and`sigs.html` webpage can be modified to support this. (This could be a good starting point for someone to learn the codebase!)

Potential `groups.yaml` schema change
```yaml
sigs:
  - name: AIDA
    description: Artificial Intelligence and Data Analytics
    chairs: Jeffrey Lai, Arjun Gupta, Shaw Kagawa
    website: https://aida.acm.illinois.edu
    email: sig-aida-request@lists.illinois.edu
    meetings:
      - topic: Data Analytics Workshops
        time: 'Sunday 2:00 PM - 3:00 PM'
        location: Siebel 1105
      - topic: AI Workshops
        time: 'Wednesday 5:00 PM - 7:00 PM'
        location: Siebel 1109
```
