### ISSUE TITLE
SIGGraph meeting time update

### ISSUE THREAD

**Issue by sahilshahpatel** [acm-uiuc/core#96]
After room reservations came in, we need to update the SIGGraph meeting time again. The new info is:
```
name: SIGGRAPH
description: Special Interest Group for Computer Graphics
chairs: Sahil Patel, Stacy Zheng, Michael Korenchan
meetings:
  - topic: General Meeting
    meetingTime: 'Mondays 4:00 PM - 5:00 PM'
    meetingLocation: Siebel Center for CS rm. 1103
website: https://acm-uiuc.github.io/siggraph/
email: siggraphuiuc@gmail.com
```
